### ISSUE TITLE
Allow user to set custom aliases

### ISSUE THREAD

**Issue by DBKenshin** [SignalK/instrumentpanel#252]
I think it would be nice to be able to set custom aliases for items. For example, with my SignalK server running on my CerboGX, I have some RuuviTag sensors. The paths are just `environment.venus.<#>.temperature` and such, which with multiple makes it difficult at a glance to know which one I'm looking at unless I've memorized each # I have each tag assigned to.

I might even try and make a PR for this myself in the next few weeks if I find the time.

**Comment by tkurki** [comment]
If your sensors match temperatures in the spec you’ll get predefined units, otherwise you’ll need to specify your own metadata.

https://signalk.org/specification/1.7.0/doc/vesselsBranch.html#vesselsregexpenvironmentoutsidetemperature
https://github.com/SignalK/signalk-server/wiki/FAQ:-Frequently-Asked-Questions#how-to-add-missing-units-and-static-data-eg-displayname

**Comment by DBKenshin** [comment]
Aha, Path Mapper would do it wouldn't it. Thanks!
