### ISSUE TITLE
Fonts are too big in firefox

### ISSUE THREAD

**Issue by rob42** [SignalK/instrumentpanel#55]
Open the instrumentpanel in firefox. The fonts are too big and overlap. I looked into the css with dev tools, but could not see the cause  or affect the display to any extent.

**Comment by tkurki** [comment]
Could you be a bit more specific? What data, what widget, what widget size?

This is what you get from http://node-master.signalk.org/instrumentpanel/  out of the box (I just moved position so that it is shown and not below the fold):

![image](https://cloud.githubusercontent.com/assets/1049678/24597409/614cc3f8-184e-11e7-9494-766c68800544.png)

Position is not pretty, but there is no generic _fonts are too big and overlap_ problem afai can see.

As the final result is a combination of individual panel's aspect ratio and `text`s' font sizes it is not a question of adjusting font sizes for just one case.

For example changing the position widget's aspect ratio by reducing height one notch results in 
![image](https://cloud.githubusercontent.com/assets/1049678/24597523/14d6ca72-184f-11e7-9930-8a4e6bcf95d8.png)

**Comment by rob42** [comment]
Its on all the panels, I didnt specify as it seems to be a firebox thing. Looks normal in chrome

**Comment by rob42** [comment]
Firefox thing. <curse>cell phone </curse>

**Comment by timmathews** [comment]
FWIW, this is how the latest version renders in Firefox 53 on Windows.

![screenshot-demo signalk org-2017-06-02-16-57-31](https://cloud.githubusercontent.com/assets/1078998/26744605/a0c1a6e4-47b4-11e7-8fbe-7aa9d8606b0e.png)

No amount of resizing seems to help
